### ISSUE TITLE
Broken webpage

### ISSUE THREAD

**Issue by R8s6** [patrik-martinko/app-bing-ai-for-firefox#1]
Hi,

Thanks for the addon!

It appears to be broken for Firefox 122.0.1 (64-bit, Linux), as of 2024-02-15, with the blanks up on the top:

![](https://i.imgur.com/toow0Do.png)

Could you please kindly debug the issue when you have time? Thank you very much.

**Comment by patrik-martinko** [comment]
Hi. This extension doesn't change or intercept the functionality of Copilot, only sets an HTTP header, so it cannot break the functionality. Copilot itself is often faulty because Microsoft updates it frequently. Unfortunately, I don't have the possibility to fix Microsoft's bugs.
